spring:
  resources:
    static-locations: "classpath:/dist"
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
  datasource:
    #    url: jdbc:mysql://sgall-mysql.default.svc.cluster.local:3306/sgfps?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    #    username: root
    #    password: mysql@123
#    url: jdbc:mysql://192.168.0.127:3306/sgfps?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://182.61.138.205:3306/sgfps?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://192.168.0.127:3306/sj?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#    password: OTAxN&hiN2Vk
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: fps
  devtools:
    restart:
      enabled: true
  session:
    timeout: 36000S
  ldap:
    #    urls: ldap://ldaps-service.default.svc.cluster.local:636  #636
    #    username: cn=admin,${spring.ldap.base}
    #    password: 1234567
    #    base: dc=example,dc=com
    urls: ldap://192.168.0.66:32301  #636
    username: cn=admin,${spring.ldap.base}
    password: 123456
    base: dc=example,dc=com


server:
#  port: 9090
  port: 8080
  max-http-header-size: 102400
  servlet:
    context-path: /sgfps
    session:
      timeout: 36000S

jasypt:
  encryptor:
    # 加密的盐值，为了安全，该配置可以放在启动参数或者命令行参数中
    password: fa7bd4edd42448aea8c9484fbce6e8cd
    # 加密所采用的算法
    algorithm: PBEWITHHMACSHA512ANDAES_256


