spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://172.33.0.1:5432/bph?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100
      connection-test-query: SELECT 1
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: SGFPSHikariCP
      idle-timeout: 600000
    #data: classpath:opf.sql
    platform: mysql
    initialization-mode: always
  application:
    name: fps
  devtools:
    restart:
      enabled: true
  session:
    timeout: 36000S
  ldap:
    urls: ldap://172.33.0.1:636  #636
    username: cn=admin,${spring.ldap.base}
    password: 123456
    base: dc=example,dc=com
server:
  port: 9090
#  port: 8080
  max-http-header-size: 102400
  servlet:
    context-path: /sgfps
    session:
      timeout: 36000S

